columns = [
    "todo",
    "in-progress",
    "review",
    "done",
]
done_column = "done"

[project]
name = "show-multiple"
key = "T"

[tui]
confirm_quit = true


[storage]
backend = "file"

[wip]
enabled = true

[display]
markdown = true
