//! CLI entrypoint for structured automation plans.

use super::*;
use pinto::automation::{
    AUTOMATION_RESULT_ENV, AUTOMATION_RESULT_PREFIX, AutomationCommandResult, AutomationPlan,
    AutomationProducerResult, AutomationReport,
};
use pinto::backlog::ItemId;
use std::collections::HashMap;
use std::io::Read;
use std::path::Path;
use std::process::Stdio;
use tokio::process::Command as ProcessCommand;

/// Execute a plan generated by an external AI agent as existing pinto CLI commands.
pub(super) async fn cmd_automate(args: AutomateArgs) -> anyhow::Result<ExitCode> {
    if args.schema {
        println!(
            "{}",
            serde_json::to_string_pretty(&AutomationPlan::json_schema())?
        );
        return Ok(ExitCode::SUCCESS);
    }

    let source = args.plan.ok_or(Error::InvalidAutomationPlan)?;
    let input = read_automation_plan(&source).await?;
    let plan = AutomationPlan::parse(&input).map_err(|_| Error::InvalidAutomationPlan)?;
    let validated = validate_automation_commands(&plan);

    if validated.iter().any(|command| command.error.is_some()) {
        let commands = validated
            .iter()
            .map(|command| AutomationCommandResult {
                index: command.index,
                command: command.name.clone(),
                status: if command.error.is_some() {
                    "invalid".to_string()
                } else {
                    "valid".to_string()
                },
                created_ids: Vec::new(),
                updated_ids: automation_target_ids(&command.argv),
                resolved_ids: automation_item_ids(&command.argv),
                error: command.error.clone(),
            })
            .collect();
        let report = AutomationReport {
            status: "invalid".to_string(),
            dry_run: args.dry_run,
            commands,
        };
        if args.json {
            print_automation_json(&report)?;
        } else {
            print_automation_validation(&report, false);
        }
        return Ok(ExitCode::from(1));
    }

    if args.dry_run {
        let dir = std::env::current_dir()?;
        let report = dry_run_automation(&dir, &validated).await?;
        if args.json {
            print_automation_json(&report)?;
        } else {
            print_automation_validation(&report, report.status == "dry_run");
        }
        return Ok(if report.status == "dry_run" {
            ExitCode::SUCCESS
        } else {
            ExitCode::from(1)
        });
    }

    let dir = std::env::current_dir()?;
    let mut results = Vec::with_capacity(validated.len());
    let mut producer_results = vec![None; validated.len()];
    let mut internal_failure = false;
    let mut failed_at = None;

    for (position, command) in validated.iter().enumerate() {
        let resolved_argv = match resolve_automation_command(&command.argv, &producer_results) {
            Ok(argv) => argv,
            Err(error) => {
                results.push(automation_resolution_failure(command, &error));
                failed_at = Some(position);
                for skipped in validated.iter().skip(position + 1) {
                    results.push(automation_skipped_result(skipped));
                }
                break;
            }
        };
        let execution = run_automation_command(&dir, &resolved_argv).await?;
        if execution.success {
            if !args.json {
                print!("{}", execution.stdout);
            }
            producer_results[position] = execution.producer_result.clone();
            results.push(automation_execution_result(
                command,
                &resolved_argv,
                &execution,
                "succeeded",
            ));
        } else {
            internal_failure = execution.exit_code != Some(1);
            results.push(automation_execution_result(
                command,
                &resolved_argv,
                &execution,
                "failed",
            ));
            failed_at = Some(position);
            for skipped in validated.iter().skip(position + 1) {
                results.push(automation_skipped_result(skipped));
            }
            break;
        }
    }

    let failed = failed_at.is_some();
    let report = AutomationReport {
        status: if failed {
            "partial_failure".to_string()
        } else {
            "completed".to_string()
        },
        dry_run: false,
        commands: results,
    };

    if args.json {
        print_automation_json(&report)?;
    } else if let Some(failed_at) = failed_at {
        let failed_command = &report.commands[failed_at];
        let index = failed_command.index.to_string();
        let completed = report
            .commands
            .iter()
            .filter(|command| command.status == "succeeded")
            .count()
            .to_string();
        let failed_count = report
            .commands
            .iter()
            .filter(|command| command.status == "failed")
            .count()
            .to_string();
        let skipped = report
            .commands
            .iter()
            .filter(|command| command.status == "skipped")
            .count()
            .to_string();
        let error = failed_command.error.as_deref().unwrap_or("unknown error");
        eprintln!(
            "{}",
            current().format(
                Message::AutomationCommandFailed,
                [
                    ("index", index.as_str()),
                    ("command", failed_command.command.as_str()),
                    ("error", error),
                ],
            )
        );
        eprintln!(
            "{}",
            current().format(
                Message::AutomationPartialFailure,
                [
                    ("index", index.as_str()),
                    ("command", failed_command.command.as_str()),
                    ("completed", completed.as_str()),
                    ("failed", failed_count.as_str()),
                    ("skipped", skipped.as_str()),
                ],
            )
        );
        for skipped_command in report
            .commands
            .iter()
            .filter(|command| command.status == "skipped")
        {
            let skipped_index = skipped_command.index.to_string();
            eprintln!(
                "{}",
                current().format(
                    Message::AutomationCommandSkipped,
                    [
                        ("index", skipped_index.as_str()),
                        ("command", skipped_command.command.as_str()),
                    ],
                )
            );
        }
    } else {
        let total = report.commands.len().to_string();
        println!(
            "{}",
            current().format(Message::AutomationCompleted, [("total", total.as_str())])
        );
    }

    Ok(if failed {
        if internal_failure {
            ExitCode::from(2)
        } else {
            ExitCode::from(1)
        }
    } else {
        ExitCode::SUCCESS
    })
}

#[derive(Debug)]
pub(super) struct ValidatedAutomationCommand {
    pub(super) index: usize,
    pub(super) argv: Vec<String>,
    pub(super) name: String,
    pub(super) error: Option<String>,
}

#[derive(Debug)]
pub(super) struct AutomationExecution {
    pub(super) success: bool,
    pub(super) exit_code: Option<i32>,
    pub(super) stdout: String,
    pub(super) stderr: String,
    pub(super) producer_result: Option<AutomationProducerResult>,
}

pub(super) async fn read_automation_plan(source: &str) -> anyhow::Result<String> {
    if source == "-" {
        let input = tokio::task::spawn_blocking(|| {
            let mut input = String::new();
            std::io::stdin().read_to_string(&mut input)?;
            Ok::<String, std::io::Error>(input)
        })
        .await??;
        return Ok(input);
    }

    let inline_json = source.trim_start().starts_with('{');
    let path = Path::new(source);
    let exists = match tokio::fs::try_exists(path).await {
        Ok(exists) => exists,
        // JSON such as `{"commands": [...]}` is not a valid Windows path. Preserve the
        // existing-file precedence while allowing the parser to report malformed inline JSON.
        Err(_error) if inline_json => return Ok(source.to_string()),
        Err(error) => {
            return Err(Error::AutomationPlanSource {
                path: path.to_path_buf(),
                message: error.to_string(),
            }
            .into());
        }
    };
    if exists {
        return tokio::fs::read_to_string(path).await.map_err(|error| {
            Error::AutomationPlanSource {
                path: path.to_path_buf(),
                message: error.to_string(),
            }
            .into()
        });
    }
    if inline_json {
        return Ok(source.to_string());
    }
    Err(Error::AutomationPlanSource {
        path: path.to_path_buf(),
        message: "file does not exist".to_string(),
    }
    .into())
}

fn validate_automation_commands(plan: &AutomationPlan) -> Vec<ValidatedAutomationCommand> {
    plan.commands()
        .iter()
        .enumerate()
        .map(|(position, argv)| {
            let parsed =
                Cli::try_parse_from(std::iter::once("pinto".to_string()).chain(argv.clone()));
            let error = match parsed {
                Err(_) => Some(current().text(Message::AutomationInvalidCommandArguments)),
                Ok(cli) => validate_automation_item_ids(&cli, argv, position, plan),
            };
            ValidatedAutomationCommand {
                index: position + 1,
                argv: argv.clone(),
                name: automation_command_name(argv),
                error,
            }
        })
        .collect()
}

fn item_id_arguments(cli: &Cli) -> Vec<&String> {
    match &cli.command {
        Command::Add(args) => args.parent.iter().chain(args.depends_on.iter()).collect(),
        Command::Split(args) => vec![&args.source],
        Command::Show(args) => args.ids.iter().collect(),
        Command::Move(args) => args
            .destination_and_ids()
            .map_or_else(Vec::new, |(_, ids)| ids.iter().collect()),
        Command::Reorder(args) => {
            let mut ids = vec![&args.id];
            if let Some(reference) = &args.before {
                ids.push(reference);
            }
            if let Some(reference) = &args.after {
                ids.push(reference);
            }
            ids
        }
        Command::Edit(args) => {
            let mut ids = vec![&args.id];
            if let Some(parent) = &args.parent {
                ids.push(parent);
            }
            ids
        }
        Command::Remove(args) => args.ids.iter().collect(),
        Command::Restore(args) => vec![&args.id],
        Command::Dep(args) => match &args.command {
            DepCommand::Add { id, depends_on } | DepCommand::Rm { id, depends_on } => {
                vec![id, depends_on]
            }
        },
        Command::Link(args) => match &args.command {
            LinkCommand::Add { id, .. } | LinkCommand::Rm { id, .. } => vec![id],
            LinkCommand::Sync { .. } => Vec::new(),
        },
        Command::Sprint(args) => match &args.command {
            SprintCommand::Add { item_id, .. } => item_id.iter().collect(),
            SprintCommand::Unassign { item_id, .. } => vec![item_id],
            SprintCommand::New { .. }
            | SprintCommand::Edit { .. }
            | SprintCommand::Remove { .. }
            | SprintCommand::Start { .. }
            | SprintCommand::Close { .. }
            | SprintCommand::List { .. }
            | SprintCommand::Burndown { .. }
            | SprintCommand::Velocity { .. }
            | SprintCommand::Capacity { .. } => Vec::new(),
        },
        Command::Init
        | Command::List(_)
        | Command::Next(_)
        | Command::Dod(_)
        | Command::Export(_)
        | Command::Import(_)
        | Command::Board(_)
        | Command::CycleTime(_)
        | Command::Rebalance(_)
        | Command::Migrate(_)
        | Command::Doctor(_)
        | Command::Undo
        | Command::Automate(_)
        | Command::Shell
        | Command::Kanban(_)
        | Command::Completion(_) => Vec::new(),
    }
}

fn validate_automation_item_ids(
    cli: &Cli,
    argv: &[String],
    position: usize,
    plan: &AutomationPlan,
) -> Option<String> {
    let localizer = current();
    let ids = item_id_arguments(cli);
    let mut allowed_placeholders = HashMap::<String, usize>::new();

    for raw in ids {
        match parse_output_reference(raw) {
            Ok(Some(reference)) => {
                if let Some(error) = validate_output_reference(reference, position, plan, localizer)
                {
                    return Some(error);
                }
                *allowed_placeholders.entry(raw.clone()).or_default() += 1;
            }
            Ok(None) => {
                if let Err(error) = raw.parse::<ItemId>() {
                    return Some(error.localized(localizer));
                }
            }
            Err(error) => return Some(error.localized(localizer)),
        }
    }

    for raw in argv.iter().skip(1) {
        let Ok(reference) = parse_output_reference(raw) else {
            return Some(format_invalid_placeholder(raw, localizer));
        };
        let Some(reference) = reference else {
            continue;
        };
        let Some(remaining) = allowed_placeholders.get_mut(raw) else {
            return Some(format_only_item_id_placeholder(raw, localizer));
        };
        if *remaining == 0 {
            return Some(format_only_item_id_placeholder(raw, localizer));
        }
        *remaining -= 1;
        if let Some(error) = validate_output_reference(reference, position, plan, localizer) {
            return Some(error);
        }
    }

    None
}

async fn run_automation_command(
    dir: &Path,
    argv: &[String],
) -> anyhow::Result<AutomationExecution> {
    let executable = std::env::current_exe()?;
    let output = ProcessCommand::new(executable)
        .args(argv)
        .current_dir(dir)
        .env(AUTOMATION_RESULT_ENV, "1")
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .await?;
    let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
    let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
    let producer_result = if output.status.success() && is_producer_command(argv) {
        Some(parse_producer_result(&stderr)?)
    } else {
        None
    };
    Ok(AutomationExecution {
        success: output.status.success(),
        exit_code: output.status.code(),
        stdout,
        stderr,
        producer_result,
    })
}

async fn dry_run_automation(
    dir: &Path,
    commands: &[ValidatedAutomationCommand],
) -> anyhow::Result<AutomationReport> {
    // Keep the source board stable while taking the snapshot. The guard also excludes normal
    // writers from changing backend/config state between the board copy and preview execution.
    let _lock = lock_board(dir).await?;
    let workspace = create_dry_run_workspace(dir).await?;
    let report = run_dry_run_commands(&workspace, commands).await;
    let cleanup = tokio::fs::remove_dir_all(&workspace).await;
    match report {
        Err(error) => {
            let _ = cleanup;
            Err(error)
        }
        Ok(report) => {
            cleanup?;
            Ok(report)
        }
    }
}

async fn run_dry_run_commands(
    workspace: &Path,
    commands: &[ValidatedAutomationCommand],
) -> anyhow::Result<AutomationReport> {
    let mut results = Vec::with_capacity(commands.len());
    let mut producer_results = vec![None; commands.len()];
    let mut failed = false;

    for (position, command) in commands.iter().enumerate() {
        let resolved_argv = match resolve_automation_command(&command.argv, &producer_results) {
            Ok(argv) => argv,
            Err(error) => {
                results.push(automation_resolution_failure(command, &error));
                for skipped in commands.iter().skip(position + 1) {
                    results.push(automation_skipped_result(skipped));
                }
                failed = true;
                break;
            }
        };
        let execution = run_automation_command(workspace, &resolved_argv).await?;
        if execution.success {
            producer_results[position] = execution.producer_result.clone();
            results.push(automation_execution_result(
                command,
                &resolved_argv,
                &execution,
                "valid",
            ));
        } else {
            results.push(automation_execution_result(
                command,
                &resolved_argv,
                &execution,
                "invalid",
            ));
            for skipped in commands.iter().skip(position + 1) {
                results.push(automation_skipped_result(skipped));
            }
            failed = true;
            break;
        }
    }

    Ok(AutomationReport {
        status: if failed {
            "invalid".to_string()
        } else {
            "dry_run".to_string()
        },
        dry_run: true,
        commands: results,
    })
}

async fn create_dry_run_workspace(dir: &Path) -> anyhow::Result<std::path::PathBuf> {
    let timestamp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_or(0, |duration| duration.as_nanos());
    let base = std::env::temp_dir();
    for attempt in 0..100_u32 {
        let workspace = base.join(format!(
            "pinto-dry-run-{}-{timestamp}-{attempt}",
            std::process::id()
        ));
        match tokio::fs::create_dir(&workspace).await {
            Ok(()) => {
                #[cfg(unix)]
                {
                    use std::os::unix::fs::PermissionsExt;
                    if let Err(error) = tokio::fs::set_permissions(
                        &workspace,
                        std::fs::Permissions::from_mode(0o700),
                    )
                    .await
                    {
                        let _ = tokio::fs::remove_dir_all(&workspace).await;
                        return Err(error.into());
                    }
                }
                let source = dir.join(".pinto");
                let destination = workspace.join(".pinto");
                if let Err(error) = copy_directory(&source, &destination).await {
                    let _ = tokio::fs::remove_dir_all(&workspace).await;
                    return Err(error);
                }
                let has_git = match tokio::fs::try_exists(dir.join(".git")).await {
                    Ok(value) => value,
                    Err(error) => {
                        let _ = tokio::fs::remove_dir_all(&workspace).await;
                        return Err(error.into());
                    }
                };
                if has_git {
                    let output = match ProcessCommand::new("git")
                        .args(["init"])
                        .current_dir(&workspace)
                        .output()
                        .await
                    {
                        Ok(output) => output,
                        Err(error) => {
                            let _ = tokio::fs::remove_dir_all(&workspace).await;
                            let message = current().format(
                                Message::AutomationDryRunGitInitFailed,
                                [("message", error.to_string().as_str())],
                            );
                            return Err(anyhow::anyhow!("{message}"));
                        }
                    };
                    if !output.status.success() {
                        let _ = tokio::fs::remove_dir_all(&workspace).await;
                        let detail = String::from_utf8_lossy(&output.stderr).trim().to_string();
                        let message = current().format(
                            Message::AutomationDryRunGitInitFailed,
                            [("message", detail.as_str())],
                        );
                        return Err(anyhow::anyhow!("{message}"));
                    }
                }
                return Ok(workspace);
            }
            Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => continue,
            Err(error) => return Err(error.into()),
        }
    }
    Err(anyhow::anyhow!(
        "{}",
        current().text(Message::AutomationDryRunWorkspaceUnavailable)
    ))
}

async fn copy_directory(source: &Path, destination: &Path) -> anyhow::Result<()> {
    let mut pending = vec![(source.to_path_buf(), destination.to_path_buf())];
    while let Some((source, destination)) = pending.pop() {
        tokio::fs::create_dir_all(&destination).await?;
        let mut entries = tokio::fs::read_dir(&source).await?;
        while let Some(entry) = entries.next_entry().await? {
            // The source lock belongs to the original board and must never become part of the
            // ephemeral preview state (or a Git commit made inside it).
            if entry.file_name() == ".lock" {
                continue;
            }
            let source_path = entry.path();
            let destination_path = destination.join(entry.file_name());
            if entry.file_type().await?.is_dir() {
                pending.push((source_path, destination_path));
            } else {
                tokio::fs::copy(source_path, destination_path).await?;
            }
        }
    }
    Ok(())
}

pub(super) fn automation_command_name(argv: &[String]) -> String {
    match (argv.first(), argv.get(1)) {
        (Some(command), Some(subcommand))
            if matches!(command.as_str(), "dep" | "link" | "sprint") =>
        {
            format!("{command} {subcommand}")
        }
        (Some(command), _) => command.clone(),
        (None, _) => "unknown".to_string(),
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct OutputReference {
    command_index: usize,
    output_index: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct PlaceholderError {
    raw: String,
}

impl PlaceholderError {
    fn localized(&self, localizer: &pinto::i18n::Localizer) -> String {
        format_invalid_placeholder(&self.raw, localizer)
    }
}

fn parse_output_reference(raw: &str) -> Result<Option<OutputReference>, PlaceholderError> {
    if !raw.contains("@command") {
        return Ok(None);
    }

    let Some(rest) = raw.strip_prefix("@command[") else {
        return Err(PlaceholderError {
            raw: raw.to_string(),
        });
    };
    let Some((command_index, rest)) = rest.split_once("].created_ids[") else {
        return Err(PlaceholderError {
            raw: raw.to_string(),
        });
    };
    let Some((output_index, suffix)) = rest.split_once(']') else {
        return Err(PlaceholderError {
            raw: raw.to_string(),
        });
    };
    if suffix.is_empty()
        && !command_index.is_empty()
        && command_index.bytes().all(|byte| byte.is_ascii_digit())
        && !output_index.is_empty()
        && output_index.bytes().all(|byte| byte.is_ascii_digit())
    {
        let command_index = command_index
            .parse::<usize>()
            .map_err(|_| PlaceholderError {
                raw: raw.to_string(),
            })?;
        let output_index = output_index
            .parse::<usize>()
            .map_err(|_| PlaceholderError {
                raw: raw.to_string(),
            })?;
        return Ok(Some(OutputReference {
            command_index,
            output_index,
        }));
    }

    Err(PlaceholderError {
        raw: raw.to_string(),
    })
}

fn format_invalid_placeholder(raw: &str, localizer: &pinto::i18n::Localizer) -> String {
    localizer.format(Message::AutomationPlaceholderInvalid, [("raw", raw)])
}

fn format_only_item_id_placeholder(raw: &str, localizer: &pinto::i18n::Localizer) -> String {
    localizer.format(Message::AutomationPlaceholderOnlyItemId, [("raw", raw)])
}

fn validate_output_reference(
    reference: OutputReference,
    position: usize,
    plan: &AutomationPlan,
    localizer: &pinto::i18n::Localizer,
) -> Option<String> {
    if reference.command_index >= plan.commands().len() {
        let index = reference.command_index.to_string();
        return Some(localizer.format(
            Message::AutomationPlaceholderUnknownCommand,
            [("index", index.as_str())],
        ));
    }
    if reference.command_index >= position {
        let index = reference.command_index.to_string();
        return Some(localizer.format(
            Message::AutomationPlaceholderFutureCommand,
            [("index", index.as_str())],
        ));
    }
    let producer = &plan.commands()[reference.command_index];
    if !is_producer_command(producer) {
        let index = reference.command_index.to_string();
        let command = automation_command_name(producer);
        return Some(localizer.format(
            Message::AutomationPlaceholderNonProducer,
            [("index", index.as_str()), ("command", command.as_str())],
        ));
    }
    None
}

fn is_producer_command(argv: &[String]) -> bool {
    matches!(
        argv.first().map(String::as_str),
        Some("add" | "a" | "split" | "spl")
    )
}

fn resolve_automation_command(
    argv: &[String],
    producer_results: &[Option<AutomationProducerResult>],
) -> Result<Vec<String>, String> {
    let localizer = current();
    argv.iter()
        .map(|raw| {
            let reference =
                parse_output_reference(raw).map_err(|error| error.localized(localizer))?;
            let Some(reference) = reference else {
                return Ok(raw.clone());
            };
            let result = producer_results
                .get(reference.command_index)
                .and_then(Option::as_ref)
                .ok_or_else(|| {
                    let index = reference.command_index.to_string();
                    localizer.format(
                        Message::AutomationPlaceholderNoResult,
                        [("index", index.as_str())],
                    )
                })?;
            let reference_text = format!(
                "@command[{}].created_ids[{}]",
                reference.command_index, reference.output_index
            );
            let count = result.created_ids.len().to_string();
            let id = result
                .created_ids
                .get(reference.output_index)
                .ok_or_else(|| {
                    localizer.format(
                        Message::AutomationPlaceholderOutOfRange,
                        [
                            ("reference", reference_text.as_str()),
                            ("count", count.as_str()),
                        ],
                    )
                })?;
            id.parse::<ItemId>().map_err(|error| {
                localizer.format(
                    Message::AutomationPlaceholderInvalidProducerId,
                    [
                        ("id", id.as_str()),
                        ("reference", reference_text.as_str()),
                        ("message", error.to_string().as_str()),
                    ],
                )
            })?;
            Ok(id.clone())
        })
        .collect()
}

pub(super) fn parsed_item_id(raw: Option<&String>) -> Option<String> {
    raw.and_then(|value| value.parse::<ItemId>().ok())
        .map(|id| id.to_string())
}

pub(super) fn automation_target_ids(argv: &[String]) -> Vec<String> {
    let Ok(cli) = Cli::try_parse_from(std::iter::once("pinto".to_string()).chain(argv.to_vec()))
    else {
        return Vec::new();
    };
    match &cli.command {
        Command::Split(args) => parsed_item_id(Some(&args.source)).into_iter().collect(),
        Command::Move(args) => args
            .destination_and_ids()
            .map_or_else(Vec::new, |(_, ids)| {
                ids.iter()
                    .filter_map(|id| parsed_item_id(Some(id)))
                    .collect()
            }),
        Command::Edit(args) => parsed_item_id(Some(&args.id)).into_iter().collect(),
        Command::Reorder(args) => parsed_item_id(Some(&args.id)).into_iter().collect(),
        Command::Remove(args) => args
            .ids
            .iter()
            .filter_map(|id| parsed_item_id(Some(id)))
            .collect(),
        Command::Restore(args) => parsed_item_id(Some(&args.id)).into_iter().collect(),
        Command::Dep(args) => match &args.command {
            DepCommand::Add { id, .. } | DepCommand::Rm { id, .. } => {
                parsed_item_id(Some(id)).into_iter().collect()
            }
        },
        Command::Link(args) => match &args.command {
            LinkCommand::Add { id, .. } | LinkCommand::Rm { id, .. } => {
                parsed_item_id(Some(id)).into_iter().collect()
            }
            LinkCommand::Sync { .. } => Vec::new(),
        },
        Command::Sprint(args) => match &args.command {
            SprintCommand::Add { item_id, .. } => item_id
                .as_ref()
                .and_then(|id| parsed_item_id(Some(id)))
                .into_iter()
                .collect(),
            SprintCommand::Unassign { item_id, .. } => {
                parsed_item_id(Some(item_id)).into_iter().collect()
            }
            _ => Vec::new(),
        },
        _ => Vec::new(),
    }
}

pub(super) fn automation_item_ids(argv: &[String]) -> Vec<String> {
    let Ok(cli) = Cli::try_parse_from(std::iter::once("pinto".to_string()).chain(argv.to_vec()))
    else {
        return Vec::new();
    };
    item_id_arguments(&cli)
        .iter()
        .filter_map(|id| parsed_item_id(Some(id)))
        .collect()
}

pub(super) fn automation_execution_result(
    command: &ValidatedAutomationCommand,
    resolved_argv: &[String],
    execution: &AutomationExecution,
    status: &str,
) -> AutomationCommandResult {
    automation_execution_result_with_localizer(command, resolved_argv, execution, status, current())
}

/// Build a command result with an explicit localizer.
///
/// The production entry point [`automation_execution_result`] forwards the process localizer
/// ([`current`]); tests inject a deterministic localizer so their English assertions do not
/// depend on the parent process locale.
pub(super) fn automation_execution_result_with_localizer(
    command: &ValidatedAutomationCommand,
    resolved_argv: &[String],
    execution: &AutomationExecution,
    status: &str,
    localizer: &pinto::i18n::Localizer,
) -> AutomationCommandResult {
    let created_ids = execution
        .producer_result
        .as_ref()
        .map_or_else(Vec::new, |result| result.created_ids.clone());
    AutomationCommandResult {
        index: command.index,
        command: command.name.clone(),
        status: status.to_string(),
        created_ids,
        updated_ids: automation_target_ids(resolved_argv),
        resolved_ids: automation_item_ids(resolved_argv),
        error: (!execution.success).then(|| {
            let error = visible_stderr(&execution.stderr);
            if error.is_empty() {
                let status = execution
                    .exit_code
                    .map_or_else(|| "unknown".to_string(), |code| code.to_string());
                localizer.format(
                    Message::AutomationCommandExited,
                    [("status", status.as_str())],
                )
            } else {
                error.to_string()
            }
        }),
    }
}

fn parse_producer_result(stderr: &str) -> anyhow::Result<AutomationProducerResult> {
    let line = stderr
        .lines()
        .find_map(|line| line.strip_prefix(AUTOMATION_RESULT_PREFIX))
        .ok_or_else(|| anyhow::anyhow!("producer command did not return a structured result"))?;
    serde_json::from_str(line)
        .map_err(|error| anyhow::anyhow!("producer returned invalid structured result: {error}"))
}

fn visible_stderr(stderr: &str) -> String {
    stderr
        .lines()
        .filter(|line| !line.starts_with(AUTOMATION_RESULT_PREFIX))
        .collect::<Vec<_>>()
        .join("\n")
        .trim()
        .to_string()
}

fn automation_resolution_failure(
    command: &ValidatedAutomationCommand,
    error: &str,
) -> AutomationCommandResult {
    AutomationCommandResult {
        index: command.index,
        command: command.name.clone(),
        status: "failed".to_string(),
        created_ids: Vec::new(),
        updated_ids: Vec::new(),
        resolved_ids: Vec::new(),
        error: Some(error.to_string()),
    }
}

fn automation_skipped_result(command: &ValidatedAutomationCommand) -> AutomationCommandResult {
    AutomationCommandResult {
        index: command.index,
        command: command.name.clone(),
        status: "skipped".to_string(),
        created_ids: Vec::new(),
        updated_ids: automation_target_ids(&command.argv),
        resolved_ids: automation_item_ids(&command.argv),
        error: Some(current().text(Message::AutomationNotExecutedAfterFailure)),
    }
}

fn print_automation_json(report: &AutomationReport) -> anyhow::Result<()> {
    println!("{}", serde_json::to_string_pretty(report)?);
    Ok(())
}

fn print_automation_validation(report: &AutomationReport, dry_run: bool) {
    for command in &report.commands {
        let index = command.index.to_string();
        let message = if command.status == "invalid" {
            Message::AutomationCommandInvalid
        } else {
            Message::AutomationCommandValid
        };
        eprintln!(
            "{}",
            current().format(
                message,
                [
                    ("index", index.as_str()),
                    ("command", command.command.as_str())
                ],
            )
        );
    }
    if dry_run {
        let total = report.commands.len().to_string();
        println!(
            "{}",
            current().format(
                Message::AutomationDryRunCompleted,
                [("total", total.as_str())]
            )
        );
    }
}
